.\"                                      -*- nroff -*-
.\" Copyright (C) 2014 Dimitris Zlatanidis
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.TH Slpkg "8" "5 2014" "slpkg"
.SH NAME
slpkg - Utility to help package management in Slackware
.SH SYNOPSIS
 \fBslpkg\fP \fB[-h]\fP \fB[-v]\fP \fB[-s script source]\fP \fB[-l all, sbo [all, sbo ...]]\fP 
\fB[-n]\fP \fB[-i [...]]\fP \fB[-u [...]]\fP \fB[-a [...]]\fP \fB[-b [...]]\fP 
\fB[-r[...]]\fP \fB[-f [...]]\fP \fB[-d [...]]\fP
.SH DESCRIPTION
\fBslpkg\fP is a terminal tool written in Python that allows the build, install, upgrade, 
remove, find and view Slackware packages contents.
.PP
It's a quick and easy way to manage your packages in slackware to a command.
.SH EXAMPLES
  \fB-h, --help            show this help message and exit\fP
  \fB-v, --verbose         print version and exit\fP
  \fB-s script source, --slackbuild script source\fP
  \fB                      auto build package\fP
  \fB-l all, sbo [all, sbo ...], --list all, sbo [all, sbo ...]\fP
  \fB                      list of installed packages\fP
  \fB-n , --network        find from SBo repositority\fP
  \fB-i  [ ...], --install  [ ...]\fP
  \fB                      install binary package\fP
  \fB-u  [ ...], --upgrade  [ ...]\fP
  \fB                      install-upgrade package with new\fP
  \fB-a  [ ...], --reinstall  [ ...]\fP
  \fB                      reinstall the same package\fP
  \fB-b  [ ...], --binary  [ ...]\fP
  \fB                      find already binary packages\fP
  \fB-r  [ ...], --remove  [ ...]\fP
  \fB                      remove package\fP
  \fB-f  [ ...], --find  [ ...]\fP
  \fB                      find if package installed\fP
  \fB-d  [ ...], --display  [ ...]\fP
  \fB                      display the contents of the package\fP

.SH GLOBAL OPTIONS
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Print the version of program and exit.
.SH COMMANDS
.PP
The following commands are available.
.SS -s script source, --slackbuild script source
\fBslpkg\fP \fB-s\fP <\fIscript\fP> <\fIsource\fP>
.PP
With this argument, build slackware package quickly and easy.
Support .tar.gz and .tar.bz2 slackbuilds archives.
.SS -l all, sbo [all, sbo ...], --list all, sbo [all, sbo ...]
\fBslpkg\fP \fB-l\fP <\fIall\fP> <\fIsbo\fP>
.PP
Two display options list, one for all packages and another
only for packages SBo.
.SS -n , --network find from SBo repositority
\fBslpkg\fP \fB-n\fP <\fIname\fP>
.PP
With this method you can find the SBo script that interests you through
the network. (www.slackbuilds.org)
.SS -i , --install install binary package
\fBslpkg\fP \fB-i\fP <\fIpackages.t?z\fP>
.PP
Installs single binary packages designed for use with the 
Slackware Linux distribution into your system.
.SS -u , --upgrade install-upgrade package with new
\fBslpkg\fP \fB-u\fP <\fIpackages.t?z\fP>
.PP
Normally upgrade only upgrades packages that are already
installed on the system, and will skip any packages that do not
already have a version installed. 'Requires root privileges'
(like slackware command upgradepkg --install-new)
.SS -a --reinstall
\fBslpkg\fP \fB-a\fP <\fIpackages.t?z\fP>
.PP
Upgradepkg usually skips packages if the exact same package
(matching name, version, arch, and build number) is already
installed on the system.'Requires root privileges' (like 
slackware command upgradepkg --reinstall)
.SS -b --binary
\fBslpkg\fP \fB-b\fP <\fIpackages.t?z\fP>
.PP
Find already binary Slackware packages in /tmp directory
.SS -r , --remove package
\fBslpkg\fP \fB-r\fP <\fIname of packages\fP>
.PP
Removes a previously installed Slackware package, while writing
a progress report to the standard output. A package may be 
specified either by the full package name (as you'd see listed in
/var/log/packages/), or by the base package name. 'Requires root
privileges' (like slackware command removepkg)
.SS -f --find
\fBslpkg\fP \fB-f\fP <\fIname of package\fP>
.PP
Find if package allready installed or not.
.SS -d --display
\fBslpkg\fP \fB-d\fP <\fIname of packages\fP>
.PP
Display the contents of the package with all descriptions.
.SH HELP OPTION
Specifying the help option displays help for slpkg itself, or a
command.
.br
For example:
  \fBslpkg \-\-help\fP - display help for slpkg
.SH EXAMPLES

$ \fBslpkg -n termcolor\fP
  Searching for termcolor from www.slackbuilds.org Please wait ...

  The `termcolor` found in --> http://slackbuilds.org/repository/14.1/python/termcolor/
  Download SlackBuild : http://slackbuilds.org/slackbuilds/14.1/python/termcolor.tar.gz
  Source Downloads : https://pypi.python.org/packages/source/t/termcolor/termcolor-1.1.0.tar.gz
  Extra Downloads : []
  Package requirements :


  Etc. download from www.slackbuilds.org the package termcolor
  http://slackbuilds.org/repository/14.1/python/termcolor/

  Two files termcolor.tar.gz and termcolor-1.1.0.tar.gz
  must be in the same directory.

$ \fBslpkg -s termcolor.tar.gz termcolor-1.1.0.tar.gz\fP

  Slackware package /tmp/termcolor-1.1.0-x86_64-1_SBo.tgz created.

$ \fBslpkg -u termcolor-1.1.0-x86_64-1_SBo.tgz\fP

  Installing new package ./termcolor-1.1.0-x86_64-1_SBo.tgz

$ \fBslpkg -r termcolor yetris\fP

  !!! WARNING !!!

  Are you sure to remove this package [y/n] y

  Package: termcolor-1.1.0-x86_64-1_SBo
  Package: yetris-2.0.1-x86_64-1_SBo
          Removing...

$ \fBslpkg -f termcolor\fP

  The package 'termcolor' is not installed on your system

$ \fBslpkg -d termcolor\fP

  The package 'termcolor' is not found

$ \fBslpkg -v\fP

  Version: x.x.x

.SH AUTHOR
Dimitris Zlatanidis <d.zlatanidis@gmail.com>
.SH COPYRIGHT
Copyright \(co 2014 Dimitris Zlatanidis

.SH SEE ALSO
installpkg(8), upgradepkg(8), removepkg(8), pkgtool(8), slackpkg(8) 
