.\"                                      -*- nroff -*-
.\" Copyright (C) 2014 Dimitris Zlatanidis
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.TH Slpkg "8" "5 2014" "slpkg"
.SH NAME
slpkg - Utility for easy management packages in Slackware
.SH SYNOPSIS
  \fBUsage: slpkg [-h] [-v] [-a script [sources...]]
                  [-b --list, --add, --remove [...]]
                  [-q --list, [...] --add, --remove]
                  [-q --build, --install, --build-install]
                  [-l all, sbo, slack, noarch]
                  [-c <repository> --upgrade --current]
                  [-s <repository> <package> --current]
                  [-f] [-t] [-n] [-i [...]] [-u  [...]]
                  [-o  [...]] [-r [...]] [-d [...]]\fp

.SH DESCRIPTION
\fBslpkg\fP is a terminal multitool in order to easy use Slackware packages.
.PP
It's a quick and easy way to manage your packages in slackware to a command.
.SH EXAMPLES
\fBUtility for easy management packages in Slackware

Optional arguments:
  -h, --help                                show this help message and exit
  -v, --version                             print version and exit
  -a, script [source...]                    auto build packages
  -b, --list, [package...] --add, --remove  add, remove packages in blacklist
  -q, --list, [package...] --add, --remove  add, remove packages in queue
      --build, --install, --build-install   build or install from queue
  -l, all, sbo, slack, noarch               list of installed packages
  -c, <repository> --upgrade --current      check for updated packages
  -s, <repository> <package> --current      download, build & install
  -f, <package>                             find installed packages
  -t, <package>                             tracking dependencies from SBo
  -n, <package>                             view packages from SBo
  -i, [package...]                          install binary packages
  -u, [package...]                          upgrade binary packages
  -o, [package...]                          reinstall binary packages
  -r, [package...]                          remove binary packages
  -d, [package...]                          display the contents

Repositories:
      SlackBuilds = sbo
      Slackware = slack '--current'\fP

.SH GLOBAL OPTIONS
.TP
\fB\-v\fP, \fB\-\-version\fP
Print the version of program and exit.
.SH COMMANDS
.PP
The following commands are available.
.SS -a script source extra
\fBslpkg\fP \fB-a\fP <\fIscript\fP> <\fIsources\fP>
.PP
With this argument, build slackware package from source quickly and easy.
.SS -b , --list <packages> -- add --remove
\fBslpkg\fP \fB-b\fP \fB--list\fP <\fIpackages\fP> \fB--add\fP \fB--remove\fP
.PP
List, add or remove packages from blacklist file. The settings here affect 
all repositories.
.SS -q , --list <packages> --add, --remove, --build, --install, --build-install
\fBslpkg\fP \fB-q\fP \fB--list\fP <\fIpackages\fP> \fB--add\fP \fB--remove\fP
.PP
List, add, or remove sbo packages from queue. If you want to remove all the packages
from the list 'slpkg -q all --remove'. (these arguments only working for the sbo repository)
.PP
\fBslpkg\fP \fB-q\fP \fB--build\fP \fB--install\fP \fB--build-install\fP
.PP
Build or install or build and install packages are queued.
.SS -l all, sbo, slack, noarch
\fBslpkg\fP \fB-l\fP \fIall\fP \fIsbo\fP \fIslack\fP \fInoarch\fP
.PP
Four display options list, sbo, slack, noarch and all packages
items that are installed on the system.
.SS -c , <repository> check if your packages is up to date
\fBslpkg\fP \fB-c\fP <\fIrepository\fP> \fI--upgrade\fP \fB--current\fP
.PP
Check your packages from Slackware official mirrors or from 
slackbuilds.org is up to date. Use '--current' to switch in current repository.
.SS -s , <repository> download, build and install package with all dependencies
\fBslpkg\fP \fB-s\fP <\fIrepository\fP> <\fIname of package\fP> \fB--current\fP
.PP
Installs or upgrade packages from the repository slackbuilds.org automatically resolving all 
dependencies of the package. Also installs the official distribution Slackware 
packages. Use '--current' to install packages from Slackware current repository.
.SS -f find packages
\fBslpkg\fP \fB-f\fP <\fIname of package\fP>
.PP
Find installed packages with view total file size. 
.SS -t , tracking dependencies
\fBslpkg\fP \fB-t\fP <\fIname of package\fP>
.PP
Tracking all dependencies of that package.
The sequence shown is that you must follow to correctly install package.
.SS -n , find packages from SBo repositority
\fBslpkg\fP \fB-n\fP <\fIname of package\fP>
.PP
With this method you can find the SBo script that interests you through
the network. (www.slackbuilds.org)
.SS -i , install binary packages
\fBslpkg\fP \fB-i\fP <\fIpackages.t?z\fP>
.PP
Installs single binary packages designed for use with the 
Slackware Linux distribution into your system.
.SS -u , install-upgrade packages with new
\fBslpkg\fP \fB-u\fP <\fIpackages.t?z\fP>
.PP
Normally upgrade only upgrades packages that are already
installed on the system, and will skip any packages that do not
already have a version installed. 'Requires root privileges'
(like slackware command upgradepkg --install-new)
.SS -o , reinstall binary packages
\fBslpkg\fP \fB-o\fP <\fIpackages.t?z\fP>
.PP
Upgradepkg usually skips packages if the exact same package
(matching name, version, arch, and build number) is already
installed on the system.'Requires root privileges' (like 
slackware command upgradepkg --reinstall)
.SS -r , remove packages
\fBslpkg\fP \fB-r\fP <\fIname of packages\fP>
.PP
Removes a previously installed Slackware package, while writing
a progress report to the standard output. A package may be 
specified either by the full package name (as you'd see listed in
/var/log/packages/), or by the base package name. If installed
packages with command 'slpkg -s sbo <package>' then write a file
in /var/log/slpkg/dep/ with all dependencies and it allows you  
can remove them all together. 'Requires root
privileges' (like slackware command removepkg)
.SS -d , display contents
\fBslpkg\fP \fB-d\fP <\fIname of packages\fP>
.PP
Display the contents of the package with all descriptions.
.SH HELP OPTION
Specifying the help option displays help for slpkg itself, or a
command.
.br
For example:
  \fBslpkg \-\-help\fP - display help for slpkg
.SH AUTHOR
Dimitris Zlatanidis <d.zlatanidis@gmail.com>
.SH HOMEPAGE
https://github.com/dslackw/slpkg
.SH COPYRIGHT
Copyright \(co 2014 Dimitris Zlatanidis

.SH SEE ALSO
installpkg(8), upgradepkg(8), removepkg(8), pkgtool(8), slackpkg(8) 
